title: Contramaré
email: contato@contramare.com.br
description: >-
  Fácil é seguir o fluxo, difícil é ir contra a maré
domain: contramare.com.br
baseurl: ""
url: "https://contramare.com.br"

# SEO and Social Media
author: Neylon Santos
lang: pt-BR
timezone: America/Sao_Paulo

# Modular Features Configuration
features:
  blog_page: true
  contact_page: true
  about_page: true

# Mapeamento de categorias para funcionalidades
category_feature_map:
  "Blog": "blog_page"
  "Sobre": "about_page"

permalink: /:categories/:title/

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
  -
    scope:
      path: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      image: "/assets/base/contramare-icon.png"
      seo:
        type: WebSite

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# SEO Plugin Configuration
seo:
  type: Person
  name: Neylon Santos
  links:
    - https://neylon.xyz

# Social Media
social:
  name: Contramaré
  links:
    - https://contramare.com.br
    - https://x.com/contramare_page

# Google Analytics
google_analytics: G-RQ21K77JYG

# Google Search Console
google_site_verification:

# Feed Configuration (jekyll-feed plugin)
feed:
  posts_limit: 20
  excerpt_only: false
  collections:
    posts:
      path: "/feed.xml"

# Image optimization
compress_images:
  images_path: "assets/uploads/**/*.{gif,png,jpg,jpeg,svg}"

# Performance and optimization
sass:
  style: compressed

# Security headers
webrick:
  headers:
    X-Frame-Options: SAMEORIGIN
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - .gitignore
