# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Contramaré
email: contato@contramare.com.br
description: >- # this means to ignore newlines until "baseurl:"
  O **Contramaré** é um blog de reflexões provocativas que desafia o senso
  comum. Nasce da inquietação com comportamentos normalizados que revelam
  imaturidade, falta de autorresponsabilidade e comodismo. Nossa missão é
  provocar, incomodar, e despertar — com textos que funcionam como espelhos e
  cutucam feridas. Não escrevemos para agradar. Escrevemos para transformar.
  Porque crescer exige confronto. E quem vai contra a maré, nunca volta igual.
domain: contramare.com.br
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://contramare.com.br" # the base hostname & protocol for your site, e.g. http://example.com

# SEO and Social Media
author: Neylon Santos
lang: pt-BR
timezone: America/Sao_Paulo

# Modular Features Configuration
features:
  quotes_page: false
  blog_page: true
  contact_page: true
  about_page: true

# Mapeamento de categorias para funcionalidades
category_feature_map:
  "Frases": "quotes_page"
  "Blog": "blog_page"
  "Sobre": "about_page"

permalink: /:categories/:title/

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category_page"
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
  -
    scope:
      path: "pages"
    values:
      layout: "page"

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# SEO Plugin Configuration
seo:
  type: Person
  name: Neylon Santos
  links:
    - https://neylon.xyz

# Social Media
social:
  name: Contramaré
  links:
    - https://contramare.com.br
    - https://x.com/contramare_page

# Google Analytics (adicione seu ID quando tiver)
google_analytics: # G-XXXXXXXXXX

# Google Search Console (adicione quando tiver)
google_site_verification: # seu-codigo-de-verificacao

# Feed Configuration (jekyll-feed plugin)
feed:
  posts_limit: 20
  excerpt_only: false
  collections:
    posts:
      path: "/feed.xml"

# Image optimization
compress_images:
  images_path: "assets/uploads/**/*.{gif,png,jpg,jpeg,svg}"

# Performance and optimization
sass:
  style: compressed

# Security headers
webrick:
  headers:
    X-Frame-Options: SAMEORIGIN
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - .gitignore
