name: Testar Conexão SSH

on:
  workflow_dispatch: # Permite acionar o workflow manualmente

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Testar conexão SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Conexão bem-sucedida!"
            echo "Usuário conectado:"
            whoami
            echo "Diretório atual:"
            pwd
            echo "Listando arquivos no diretório home:"
            ls -la ~/